#  defaults must be a list because composition is order sensitive
defaults:
    - task: cls
    - data: scannet3d
    - model: ssg
    - task_data_model: ${defaults.0.task}-${defaults.1.data}-${defaults.2.model}
    
hydra:
  run:
    dir: outputs

gpus:
    - 0

optimizer: ???

task_data_model: ???

model: ???

distrib_backend: dp
