#  defaults must be a list because composition is order sensitive
defaults:
    - task: cls # retr
    - data: scannet3d # scanrefer3d
    - model: ssg    # cosine
    - task_data_model: ${defaults.0.task}-${defaults.1.data}-${defaults.2.model}
    
hydra:
  run:
    dir: outputs

gpus:
    - 0

optimizer: ???

task_data_model: ???

model: ???
exp_name: name
distrib_backend: dp
